name: API Action

on:
    workflow_dispatch:
        inputs:
            selectedConfigType:
                description: 'Configuration Type'
                required: true
            productpath:
                description: 'Product Path'
                required: true
            projectdir:
                description: 'Project Directory'
                required: true
            projectname:
                description: 'Project Name'
                required: true
            environment:
                description: 'Environment'
                required: true
            tests:
                description: 'Test(s) to run'
                required: true
            junitDir:
                description: 'JunitDir'
                required: false

jobs:

    WebUI-Action:
        runs-on: self-hosted
        name: Execute API Test
        steps:
         - name: Execute Test
           uses: SonaHJ/APIAction@main
           with:
            selectedConfigType: '${{ github.event.inputs.selectedConfigType }}'
            productpath: '${{ github.event.inputs.productpath }}'
            projectdir: '${{ github.event.inputs.projectdir }}'
            projectname: '${{ github.event.inputs.projectname }}'
            environment: '${{ github.event.inputs.environment }}'
            tests: '${{ github.event.inputs.tests }}'
            junitDir: '${{ github.event.inputs.junitDir }}'
